apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-set-header: Authorization Bearer $http_authorization
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.org/proxy-pass-headers: "Authorization"
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   auth_request_set $token $upstream_http_x_auth_request_access_token;
    #   add_header 'Authorization' $token;
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header Authorization $http_authorization;
      proxy_pass_header Authorization;
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   proxy_set_header Authorization $http_authorization;
    #   proxy_pass_header Authorization;
spec:
  # ingressClassName: nginx
  tls:
    - hosts:
        - plantaludum.org
      secretName: plantaludum-tls
  rules:
    - host: plantaludum.org
      http:
        paths:
          ################
          # URL ROUTING #
          ################
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: django-cluster-ip-service
                port:
                  number: 8000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: django-cluster-ip-service
                port:
                  number: 8000
          ##########################
          # STATIC FOLDER ROUTING #
          ##########################
          - path: /static/admin/
            pathType: Prefix
            backend:
              service:
                name: static-assets-cluster-ip-service
                port:
                  number: 8000
          - path: /static/rest_framework/
            pathType: Prefix
            backend:
              service:
                name: static-assets-cluster-ip-service
                port:
                  number: 8000
          - path: /static/
            pathType: Prefix
            backend:
              service:
                name: react-cluster-ip-service
                port:
                  number: 3000
          - path: /media/
            pathType: Prefix
            backend:
              service:
                name: react-cluster-ip-service
                port:
                  number: 3000
          ################
          # URL ROUTING #
          ################
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react-cluster-ip-service
                port:
                  number: 3000
