# Generated by Django 4.2.1 on 2024-02-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_games_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identifications',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
