# Generated by Django 4.2.1 on 2023-12-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_userplayeddeck_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplayeddeck',
            name='current_stars',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
        migrations.AlterField(
            model_name='userplayeddeck',
            name='level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
    ]
