# Generated by Django 4.2.1 on 2024-03-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_userplayeddeck_current_stars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplayeddeck',
            name='last_played',
            field=models.DateField(auto_now=True),
        ),
    ]
