# Generated by Django 4.2.1 on 2024-03-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_userplayeddeck_last_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplayeddeck',
            name='last_played',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
