apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    deployment: redis
spec:
  selector:
    matchLabels:
      pod: redis
  template:
    metadata:
      labels:
        pod: redis
    spec:
      containers:
      - name: master
        image: redis
        ports:
        - containerPort: 6379
