apiVersion: v1
kind: ConfigMap
metadata:
  name: app-variables
data:
  # for postgres
  POSTGRES_USER: postgres_user
  POSTGRES_DB: plantaludumdb

  # for backend
  DJANGO_ENV: development
  DEBUG: "1"
  SECRET_KEY: fi*#%n=gs5$gzl+)si(p10cy^npmlvnxna^!y9^2qeeyt0bt%*
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_ADMIN_USER: Instelce
  DJANGO_ADMIN_EMAIL: "instelce@protonmail.com"

  # for db
  DATABASE: postgres
  DB_ENGINE: django.db.backends.postgresql_psycopg2
  DB_NAME: plantaludumdb
  DB_USER: postgres_user
  DB_HOST: postgres-cluster-ip-service
  DB_PORT: "5432"