###########################
# Job
###########################
apiVersion: batch/v1
kind: Job
metadata:
  name: django-job
spec:
  template:
    spec:
      containers:
      - name: django-job-container
        image: instelce/django_dev_image:latest
        command: ["bash", "-c", "/usr/src/app/entrypoint.sh"]
        env:
          # Django settings
          - name: DJANGO_ENV
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DJANGO_ENV
          - name: SECRET_KEY
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: SECRET_KEY
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DEBUG
          - name: DJANGO_ALLOWED_HOSTS
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DJANGO_ALLOWED_HOSTS
          # Database config
          - name: DATABASE
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DATABASE
          - name: DB_ENGINE
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DB_ENGINE
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: DB_PASSWORD
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DB_HOST 
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DB_PORT
          # Django admin
          - name: DJANGO_ADMIN_USER
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DJANGO_ADMIN_USER
          - name: DJANGO_ADMIN_EMAIL
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DJANGO_ADMIN_EMAIL
          - name: DJANGO_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: DJANGO_ADMIN_PASSWORD
          - name: REDIS_HOST
            value: redis-service
      restartPolicy: Never
  backoffLimit: 4