# Generated by Django 4.2.1 on 2024-02-04 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_userplayeddeck_current_stars_and_more'),
        ('identifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='decks.deck'),
        ),
    ]
