# Generated by Django 4.2.1 on 2024-02-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifications', '0004_identificationanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificationanswer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
