apiVersion: v1
kind: ConfigMap
metadata:
  name: app-variables
data:
  # for postgres
  POSTGRES_USER: postgres_user
  POSTGRES_DB: plantaludumdb

  # for backend
  DJANGO_ENV: production
  DEBUG: "0"
  SECRET_KEY: $gu)bv_*0uz7k*%fb)86xa%)&c^auabqkmbz6l)!zf#tl@mkh+
  DJANGO_ALLOWED_HOSTS: "plantaludum.org [::1]"
  CORS_ALLOWED_ORIGINS: "https://plantaludum.org http://127.0.0.1:3000 http://localhost:3000"
  DJANGO_ADMIN_USER: celestin
  DJANGO_ADMIN_EMAIL: "celestin.besson@proton.me"

  # for db
  DATABASE: postgres
  DB_ENGINE: django.db.backends.postgresql_psycopg2
  DB_NAME: plantaludumdb
  DB_USER: postgres_user
  DB_HOST: postgres-cluster-ip-service
  DB_PORT: "5432"

  VITE_MODE: prod