apiVersion: v1
kind: ConfigMap
metadata:
  name: app-variables
data:
  # for postgres
  POSTGRES_USER: postgres_user
  POSTGRES_DB: plantaludumdb

  # for backend
  DJANGO_ENV: production
  DEBUG: "0"
  SECRET_KEY: fi*#%n=gs5$gzl+)si(p10cy^npmlvnxna^!y9^2qeeyt0bt%*
  DJANGO_ALLOWED_HOSTS: "192.168.59.111 [::1]"
  CORS_ALLOWED_ORIGINS: "http://192.168.59.111:3000 http://127.0.0.1:3000 http://localhost:3000"
  DJANGO_ADMIN_USER: Instelce
  DJANGO_ADMIN_EMAIL: "instelce@protonmail.com"

  # for db
  DATABASE: postgres
  DB_ENGINE: django.db.backends.postgresql_psycopg2
  DB_NAME: plantaludumdb
  DB_USER: postgres_user
  DB_HOST: postgres-cluster-ip-service
  DB_PORT: "5432"

  VITE_MODE: prod