apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubecert
spec:
  secretName: cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: plantaludum.org
  dnsNames:
  - plantaludum.org 